version: "2"
services:
  web:
    image: tomcat:8
    volumes:
      - "./shiro/shiro.war:/usr/local/tomcat/webapps/shiro.war"
    ports:
      - "127.0.0.1:38000:80"
    entrypoint:
      - "catalina.sh"
      - "run"d